### ISSUE TITLE
Need Some Help!!!

### ISSUE THREAD

**Issue by YaseenYo** [jack-williams/jack-williams.github.io#1]
Hello @jack-williams , its Mohammed here. I am completely new to open source, so I tried looking some projects to contribute, And I found TypeScript. I am not getting where to start with. So pls can you help me get started, It would be really helpful...

**Comment by jack-williams** [comment]
I hope these links may be helpful:

https://dev.to/remojansen/learn-how-to-contribute-to-the-typescript-compiler-on-github-through-a-real-world-example-4df0

https://blog.andrewbran.ch/debugging-the-type-script-codebase/

https://github.com/microsoft/TypeScript/blob/main/CONTRIBUTING.md

**Comment by YaseenYo** [comment]
Thanks a lot!!!
